services:
  - type: web
    name: recipe-craft-ai
    env: python
    plan: free

    buildCommand: pip install -r backend/requirements.txt

    startCommand: gunicorn backend.app:app

    envVars:
      - key: OPENAI_API_KEY
        sync: false

      - key: GEMINI_API_KEY
        sync: false
