def generate_recipe(prompt: str) -> dict:
    """Generate a simple placeholder recipe based on the prompt."""
    title = 'Best Recipe'
    recipe_ingredients = ['1 cup flour', '2 eggs', '1/2 cup milk']
    instructions = [
        'Mix ingredients together until smooth.',
        'Preheat oven to 180°C (350°F).',
        'Bake for 20 minutes or until golden brown.'
    ]
    notes = 'This is a placeholder recipe generated by Recipe-Craft-AI.'

    if prompt:
        parts = [part.strip() for part in prompt.split('|') if part.strip()]
        ingredient_part = ''
        extra_parts = []
        for part in parts:
            if part.lower().startswith('ingredients:'):
                ingredient_part = part[len('ingredients:'):].strip()
            else:
                extra_parts.append(part)

        ingredients = [item.strip() for item in ingredient_part.split(',') if item.strip()]
        if ingredients:
            title = f"Ultimate {ingredients[0].title()} Recipe"
            recipe_ingredients = [f'1 cup {ingredients[0]}']
            if len(ingredients) > 1:
                recipe_ingredients += [f'1/2 cup {ingredients[1]}']
            recipe_ingredients += ['Salt to taste', '1 tablespoon olive oil', 'Fresh herbs for garnish']
            instructions = [
                f'Prepare the {ingredients[0]} and {ingredients[1] if len(ingredients) > 1 else "other ingredients"}.',
                'Heat oil in a pan and add the ingredients until cooked through.',
                'Season, garnish, and serve hot.'
            ]
            notes = 'A tasty recipe created from your ingredients prompt.'

        if extra_parts:
            details_text = ' '.join(extra_parts)
            notes += f' {details_text}'

    return {
        'title': title,
        'ingredients': recipe_ingredients,
        'instructions': instructions,
        'notes': notes
    }
